AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Cloud Resume Challenge Back-End (Visitor Counter)

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CloudResumeCountFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cloud-resume-counter/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CloudResumeCountTable
      Events:
        CloudResumeCount:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /visit_count
            Method: get

  CloudResumeCountTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: WebsiteVisitCounts
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "Website"
          AttributeType: "S"
        - AttributeName: "VisitorCount"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "Website"
          KeyType: "HASH"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CloudResumeCountApi:
    Description: "API Gateway endpoint URL for Prod stage for Cloud Resume Count Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/visit_count/"
  CloudResumeCountFunction:
    Description: "Cloud Resume Count Function ARN"
    Value: !GetAtt CloudResumeCountFunction.Arn
  CloudResumeCountIamRole:
    Description: "Implicit IAM Role created for Cloud Resume Count function"
    Value: !GetAtt CloudResumeCountFunctionRole.Arn
