AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Cloud Resume Challenge Back-End (Visitor Counter)

Globals:
  Function:
    Timeout: 10
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  CloudResumeCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: cloud-resume-count-function
      CodeUri: cloud-resume-counter/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CloudResumeCountTable
      Environment:
        Variables:
          TABLE_NAME: "WebsiteVisitCounts"
      Events:
        CloudResumeCount:
          Type: Api
          Properties:
            Path: /visit_count
            Method: post

  CloudResumeCountTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: WebsiteVisitCounts
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "Website"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "Website"
          KeyType: "HASH"

Outputs:
  CloudResumeCountApi:
    Description: "API Gateway endpoint URL for Prod stage for Cloud Resume Count Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/visit_count/"
  CloudResumeCountFunction:
    Description: "Cloud Resume Count Function ARN"
    Value: !GetAtt CloudResumeCountFunction.Arn
  CloudResumeCountIamRole:
    Description: "Implicit IAM Role created for Cloud Resume Count function"
    Value: !GetAtt CloudResumeCountFunctionRole.Arn
